//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BooksManagement.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BooksManagement.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _803 {
            get {
                object obj = ResourceManager.GetObject("803", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap add {
            get {
                object obj = ResourceManager.GetObject("add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap book_2 {
            get {
                object obj = ResourceManager.GetObject("book-2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除此分类后，其中所有文件将被移动到&quot;未分类&quot;文件夹下，确认删除此类别吗？.
        /// </summary>
        internal static string CategoryForm_btnDeleteCategory_Click_deleteCategoryText {
            get {
                return ResourceManager.GetString("CategoryForm_btnDeleteCategory_Click_deleteCategoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确认删除分类？.
        /// </summary>
        internal static string CategoryForm_btnDeleteCategory_Click_deleteCategoryTitle {
            get {
                return ResourceManager.GetString("CategoryForm_btnDeleteCategory_Click_deleteCategoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 书库.
        /// </summary>
        internal static string CategoryForm_InitializeUI_bookLibrary {
            get {
                return ResourceManager.GetString("CategoryForm_InitializeUI_bookLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 此分类不可删除！.
        /// </summary>
        internal static string CategoryManagement_DeleteTreeNode_couldNotDeleteCategory {
            get {
                return ResourceManager.GetString("CategoryManagement_DeleteTreeNode_couldNotDeleteCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件&quot;{0}&quot;在&quot;{1}&quot;中已存在，点击Yes覆盖此文件；点击No丢掉要移动的文件。.
        /// </summary>
        internal static string CategoryManagement_DeleteTreeNode_fileAlreadyExistText {
            get {
                return ResourceManager.GetString("CategoryManagement_DeleteTreeNode_fileAlreadyExistText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件重复.
        /// </summary>
        internal static string CategoryManagement_DeleteTreeNode_fileAlreadyExistTitle {
            get {
                return ResourceManager.GetString("CategoryManagement_DeleteTreeNode_fileAlreadyExistTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 移动文件&quot;{0}&quot;出错!
        ///
        ///{1}.
        /// </summary>
        internal static string CategoryManagement_DeleteTreeNode_moveFileError {
            get {
                return ResourceManager.GetString("CategoryManagement_DeleteTreeNode_moveFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 错误.
        /// </summary>
        internal static string Error_Title {
            get {
                return ResourceManager.GetString("Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加电子书.
        /// </summary>
        internal static string MainForm_tsmiSelectFiles_Click_addBooks {
            get {
                return ResourceManager.GetString("MainForm_tsmiSelectFiles_Click_addBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加文件错误：.
        /// </summary>
        internal static string MainForm_tsmiSelectFiles_Click_ErrorAddBooks {
            get {
                return ResourceManager.GetString("MainForm_tsmiSelectFiles_Click_ErrorAddBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加文件夹错误：.
        /// </summary>
        internal static string MainForm_tsmiSelectFolder_Click_addBooksFolderError {
            get {
                return ResourceManager.GetString("MainForm_tsmiSelectFolder_Click_addBooksFolderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择电子书文件夹.
        /// </summary>
        internal static string MainForm_tsmiSelectFolder_Click_addBooksFolderPlease {
            get {
                return ResourceManager.GetString("MainForm_tsmiSelectFolder_Click_addBooksFolderPlease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 乌合之众.
        /// </summary>
        internal static string MainForm_tsmiShowList_Click_testBookName {
            get {
                return ResourceManager.GetString("MainForm_tsmiShowList_Click_testBookName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pen {
            get {
                object obj = ResourceManager.GetObject("pen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap remove {
            get {
                object obj = ResourceManager.GetObject("remove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap search {
            get {
                object obj = ResourceManager.GetObject("search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap search_2 {
            get {
                object obj = ResourceManager.GetObject("search-2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
